### DISCUSSION TITLE
Strange behavior of pots

### DISCUSSION THREAD

**Discussion by mattjoyce** [shanteacontrols/OpenDeck#143] [Q&A]
I built a prototype with 5 pots, connected via a 4076 multiplexer, using a STM32F401CCU
What is strange is that at full rotation they show a midi value of 103, the voltage is 4.66v, it actually passes through 127 (4.2v) and then the midi value drops to 103.   Every pot I tested has this condition.   

One pot does not register, and it's not the physical device, I switch them around, Analog 0 does not register.

**Comment by paradajz** [comment]
STM32 ADC is 3V, not 5V.

**Reply by mattjoyce** [reply]
Thank you I misunderstood the schematic of the OpenDeck mini, where is show v5 supply to 4067, and made a wrong assumption.
It's exciting to see it working!

Do you have a any thoughts about the inactive input to the 4067.
I swapped out for another 4067 and problem persists.
It's #4 in Opendeck gui, 0 - 3 work fine.  I switch around my input cable reversing the physical pot order, it's the same input in Opendeck that does show anything other than 0.

**Comment by paradajz** [comment]
Can you please post the full schematic you're using?

**Reply by mattjoyce** [reply]
The 4067 is a common daughter board variant.

**Comment by mattjoyce** [comment]
[Schematic](https://imgur.com/a/zWYYVAQ)

**Comment by paradajz** [comment]
Vcc of the multiplexer should be connected to +3V. On OpenDeck Mini it's connected to 5V because AVR is a 5V MCU.

But wait, did you specify your custom YAML file?

**Reply by mattjoyce** [reply]
Yes, I had that setup like this, except I only had Index going from 0 - 4

```
  mcu: "stm32f401cc"
  extClockMhz: 25
  usb: true
  analog:
    extReference: false
    type: "4067"
    multiplexers: 1
    pins:
      s0:
        port: "A"
        index: 7
      s1:
        port: "A"
        index: 10
      s2:
        port: "A"
        index: 6
      s3:
        port: "A"
        index: 15
      z0:
        port: "A"
        index: 3
    indexing:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
```
Once I added the other index number, and looked in configurator, I could see that the missing input is number 8.
So 0,1,2,3,8 in configurator, is 0,1,2,3,4 on the 4067.
Again, more assumptions on my part, I thought the numbering on the 4067, would correspond to the index in the yaml config.

I have switch to v3.3 for 4067 supply.
