### DISCUSSION TITLE
Errors Building custom firmware + thanks!

### DISCUSSION THREAD

**Discussion by reelex** [shanteacontrols/OpenDeck#150] [Q&A] [answered]
Dear paradajz and community,

I have a problem with building a custom firmware but first I want to thank you paradajz! I am not into programming at all and your project allows me to realize my dream midi-controller. I'm so glad I found your website. I have not been on github before and I can't believe how openly you share your work. There is really something utopian about this open-source-mindset and I hope I will be able to give something back to the community or directly to you paradajz in future. I make (sound) art and electronic music and I can 3d-design and 3d-print stuff. If I can somehow help with that, it would be a pleasure to me. (You can get an idea of what I do here: https://pavilion27.com/salariu/ The Speaker cube for example is 3d-designed and printed...)

Okay now to my problem:
I'm using a blackpill411 and I'm working on Ubuntu 20.04 in a virtualbox in Win 10.
I used the amazing Wiki and followed it step by step.
I am able to build a standard blackpill411 firmware with the YAML-file already provided in the config folder.
I already flashed it on to the board and it works like a charm.

Okay so that gave me the impression everything is set up correctly and all I need now is a correct YAML-file for my custom board - or am I missing something?
Trying to not make any mistakes I just used the standard blackpill411-file and edited to go with 4 multiplexers.
The rest is identical to the standard blackpill411 YAML. 
```
 analog:
    extReference: true
    filter:
      median: true
      ema: true
    type: "4067"
    multiplexers: 4
    pins:
      s0:
        port: "A"
        index: 1
      s0:
        port: "A"
        index: 2
      s0:
        port: "A"
        index: 3
      s0:
        port: "A"
        index: 4
      z0:
        port: "A"
        index: 5
      z1:
        port: "A"
        index: 6        
      z3:
        port: "A"
        index: 7
      z4:
        port: "B"
        index: 1          
```
when I run the make command I get this:

![grafik](https://user-images.githubusercontent.com/104325628/165071052-018a2cd9-1cd0-4a3d-b990-85f001cc39ac.png)
![grafik](https://user-images.githubusercontent.com/104325628/165071131-2aa9f4f6-a170-4e95-b2b5-2ce7adb33a77.png)

I tried to find out what the problem is for hours now, looked into the wiki again and again, tried different YAML-file setups but I just can't figure it out. :/ Can anyone help me? Did I forget something?

**Comment by paradajz** [comment, marked as answer]
Hey,

I'm glad you like my work. 4067 mulitplexer uses 4 pins for controlling which pin is active: S0, S1, S2 and S3 (lowercase in the config file). All these signals are named `s0` in your config file. Just change it to correct order (config below also fixes the order of z pins):

```
  analog:
    type: "4067"
    multiplexers: 4
    pins:
      s0:
        port: "A"
        index: 1
      s1:
        port: "A"
        index: 2
      s2:
        port: "A"
        index: 3
      s3:
        port: "A"
        index: 4
      z0:
        port: "A"
        index: 5
      z1:
        port: "A"
        index: 6
      z2:
        port: "A"
        index: 7
      z3:
        port: "B"
        index: 1 
```
