### DISCUSSION TITLE
Flashing Arduino Mega 2560, failing with step…

### DISCUSSION THREAD

**Discussion by stllvdv** [shanteacontrols/OpenDeck#212] [Q&A] [answered]
Hi @paradajz et al.,

Trying to flash an Arduino Mega 2560, but unsuccessful so far. Running Ubuntu 22.04 through Parallels on latest macOS Ventura. Been following [Flashing AVR boards](https://github.com/shanteacontrols/OpenDeck/wiki/Flashing-AVR-boards) thoroughly with some minor issues (obsolete cmake version, missing avrdude), but got those fixed I think. Currently failing with the last step "**sudo ./scripts/flash.sh**" — Made sure to check that Arduino IDE states that the board is connected to ttyACMX with X == 0 so "0" should be correct, shouldn't it?

`avrdude: see_open(): can't open device "/dev/0": no such file or directory`

Warm regards.

**Comment by paradajz** [comment, marked as answer]
It's `ttyACM0`, not just `0`

**Comment by stllvdv** [comment]
Thanks for allowing me to be stupid; means I get the chance to learn fast/er. Process starts to initialize now, but results in:

```
avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.
```

**Comment by paradajz** [comment]
That usually means that the connections are wrong. Or the port is wrong. Verify both.

**Comment by stllvdv** [comment]
Thanks, again. The 10/Reset to 5/Reset was wrong indeed. Once fixed I was able to successfully flash both **atmega2560** and **atmega16u2** I think… Unfortunately OpenDeck board isn't yet found through [config.shanteacontrols.com](https://config.shanteacontrols.com/) when connected through USB using latest Chrome browser. Would I need to flash the USB as well?

**Reply by paradajz** [reply]
I think I've messed up boot delays. It also doesn't work on my board, but, once I press reset on the board while plugged in, it is recognized. Can you try the same?

**Reply by stllvdv** [reply]
Nope, doesn't seem to fix it here.

**Reply by paradajz** [reply]
Try reflashing both mega2560 and mega16u2 with the attached binaries.

[mega.zip](https://github.com/shanteacontrols/OpenDeck/files/11859980/mega.zip)

**Reply by stllvdv** [reply]
Cool, thanks. Will be back here in 15 minutes…

**Reply by stllvdv** [reply]
LOVE it. Thank you. Connected. This is really cool. I'll probably be around with more questions, but just wanted to say: thank you. This is all so cool, well done + your support has been super kind and helpful.

**Reply by paradajz** [reply]
Alright, great. I'll release the new version then!

**Comment by paradajz** [comment]
Post your entire YAML config.

**Reply by stllvdv** [reply]
```
---
  mcu: "atmega2560"
  extClockMhz: 16
  usb: false
  uart:
    usbLink:
      channel: 0
      type: "device"
    dinMIDI:
      channel: 1
  i2c:
    display:
      channel: 0
  buttons:
    type: "native"
    pins:
    -
      port: "B"
      index: 1
    -
      port: "B"
      index: 3
    -
      port: "L"
      index: 1
    -
      port: "L"
      index: 3
    -
      port: "L"
      index: 5
    -
      port: "L"
      index: 7
    -
      port: "G"
      index: 1
    -
      port: "D"
      index: 7
    -
      port: "C"
      index: 1
    -
      port: "C"
      index: 3
    -
      port: "C"
      index: 5
    -
      port: "C"
      index: 7
    -
      port: "A"
      index: 6
    -
      port: "A"
      index: 4
    -
      port: "A"
      index: 2
    -
      port: "A"
      index: 0
    -
      port: "B"
      index: 0
    -
      port: "B"
      index: 2
    -
      port: "L"
      index: 0
    -
      port: "L"
      index: 2
    -
      port: "L"
      index: 4
    -
      port: "L"
      index: 6
    -
      port: "G"
      index: 0
    -
      port: "G"
      index: 2
    -
      port: "C"
      index: 0
    -
      port: "C"
      index: 2
    -
      port: "C"
      index: 4
    -
      port: "C"
      index: 6
  analog:
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 8
    pins:
      s0:
        port: "A"
        index: 7
      s1:
        port: "A"
        index: 5
      s2:
        port: "A"
        index: 3
      s3:
        port: "A"
        index: 1
      z0:
        port: "F"
        index: 0
      z1:
        port: "F"
        index: 1
      z2:
        port: "F"
        index: 2
      z3:
        port: "F"
        index: 3
      z4:
        port: "F"
        index: 4
      z5:
        port: "F"
        index: 5
      z6:
        port: "F"
        index: 6
      z7:
        port: "F"
        index: 7
  leds:
    external:
      type: "native"
      pins:
      -
        port: "J"
        index: 0
      -
        port: "J"
        index: 1
      -
        port: "E"
        index: 4
      -
        port: "E"
        index: 5
      -
        port: "G"
        index: 5
      -
        port: "E"
        index: 3
      -
        port: "H"
        index: 3
      -
        port: "H"
        index: 4
      -
        port: "H"
        index: 5
      -
        port: "H"
        index: 6
      -
        port: "B"
        index: 4
      -
        port: "B"
        index: 5
      -
        port: "B"
        index: 6
      -
        port: "B"
        index: 7

```

**Comment by paradajz** [comment]
That configuration uses too much RAM. Another reason why I recommend against Arduino for new/large designs. The mega2560 won't boot because of that.

**Reply by stllvdv** [reply]
Interesting, thanks. Kicked the buttons and LEDs, kept only the multiplexers, still too much apparently…

EDIT: new YML, flashed again, now it's working with 64 analog inputs.
EDIT: new YML, flashed again, now it seems to be working with 96 analog inputs.
EDIT: new YML, flashed again, see below for 128 analog inputs…?

**Reply by stllvdv** [reply]
New YML, flashed again, seems to allow for 128 analog inputs and 2 presets.

```
---
  mcu: "atmega2560"
  extClockMhz: 16
  usb: false
  uart:
    usbLink:
      channel: 0
      type: "device"
    dinMIDI:
      channel: 1
  analog:
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 8
    pins:
      s0:
        port: "A"
        index: 7
      s1:
        port: "A"
        index: 5
      s2:
        port: "A"
        index: 3
      s3:
        port: "A"
        index: 1
      z0:
        port: "F"
        index: 0
      z1:
        port: "F"
        index: 1
      z2:
        port: "F"
        index: 2
      z3:
        port: "F"
        index: 3
      z4:
        port: "F"
        index: 4
      z5:
        port: "F"
        index: 5
      z6:
        port: "F"
        index: 6
      z7:
        port: "F"
        index: 7
```
