### DISCUSSION TITLE
4051 Yaml Check

### DISCUSSION THREAD

**Discussion by feedbackl00p** [shanteacontrols/OpenDeck#219] [General]
Im having a little trouble implementing the 4051 on the Pico. I suspect the issue is the 3.3v problem mentioned in the Opendeck doco, even though my variant should work at 3.3v according to the datasheet. 

Id just like to have this Yaml checked to see if it should be working as is or if ive made a silly mistake. 

Pins 6,7,8 are tied to ground, pin 16 to 3.3v. 
Decoupling cap between power and ground pin. 

```
---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 1
        tx:
          port: "0"
          index: 0
    touchscreen:
      pins:
        rx:
          port: "0"
          index: 5
        tx:
          port: "0"
          index: 4
      components: 64
  i2c:
    display:
      pins:
        sda:
          port: "0"
          index: 16
        scl:
          port: "0"
          index: 17
  buttons:
    type: "native"
    extPullups: false
    pins:
    -
      port: "0"
      index: 2
    -
      port: "0"
      index: 3
    -
      port: "0"
      index: 10
  analog:
    type: "4051"
    inputVoltage: "3.3"
    multiplexers: 1
    pins:
      s0:
        port: "0"
        index: 11
      s1:
        port: "0"
        index: 12
      s2:
        port: "0"
        index: 13
      z0:
        port: "0"
        index: 28
  leds:
    external:
      type: "native"
      pins:
      -
        port: "0"
        index: 14
      -
        port: "0"
        index: 15
      -
        port: "0"
        index: 22
      -
        port: "0"
        index: 21
      -
        port: "0"
        index: 20
      -
        port: "0"
        index: 19
      -
        port: "0"
        index: 18
```
