### DISCUSSION TITLE
MUX ON MUX with RP2040

### DISCUSSION THREAD

**Discussion by stllvdv** [shanteacontrols/OpenDeck#223] [Q&A]
Hello @paradajz et al.,

Troubleshooting… Looking into the [MUX ON MUX configurations.](https://github.com/shanteacontrols/OpenDeck/wiki/Creating-custom-board-variant#mux-on-mux) Currently testing with 1x 4067 as controller plus 1x 4067 as node with 1x pot attached; not getting any activity so far, so wondering if my config file would be correct to start with. This at least gives 256 analog inputs within the control surface:

```
---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 1
        tx:
          port: "0"
          index: 0
  analog:
    type: "muxonmux"
    inputVoltage: "3.3"
    pins:
      controller:
        s0:
          port: "0"
          index: 10
        s1:
          port: "0"
          index: 11
        s2:
          port: "0"
          index: 12
        s3:
          port: "0"
          index: 13
        z:
          port: "0"
          index: 26
      nodes:
        s0:
          port: "0"
          index: 6
        s1:
          port: "0"
          index: 7
        s2:
          port: "0"
          index: 8
        s3:
          port: "0"
          index: 9
```
