### DISCUSSION TITLE
STM32F4 with 74HC165, buttons are constantly updating/receiving values…

### DISCUSSION THREAD

**Discussion by stllvdv** [shanteacontrols/OpenDeck#229] [Q&A] [answered]
Hi @paradajz, Trying to add [shift registers](https://github.com/shanteacontrols/OpenDeck/wiki/Creating-custom-board-variant#shift-register) to a STM32F4 Black Pill, but could need so help. Buttons are working mostly as expected, but constantly flashing while activity shows that the MCU is constantly updating/receiving values?

MCU to 74HC165: "data" needs to be connected to pin 9, "clock" to pin 2, "latch" to pin 1… correct?

YAML-file is configured as follows:

```
---
  mcu: "stm32f401cc"
  extClockMhz: 25
  usb: true
  uart:
    dinMIDI:
      channel: 0
  buttons:
    type: "shiftRegister"
    shiftRegisters: 1
    pins:
      data:
        port: "B"
        index: 7
      clock:
        port: "B"
        index: 8
      latch:
        port: "B"
        index: 9
  analog:
    type: "4067"
    inputVoltage: "3.3"
    multiplexers: 6
    pins:
      s0:
        port: "B"
        index: 12
      s1:
        port: "B"
        index: 13
      s2:
        port: "B"
        index: 14
      s3:
        port: "B"
        index: 15
      z0:
        port: "A"
        index: 0
      z1:
        port: "A"
        index: 1
      z2:
        port: "A"
        index: 2
      z3:
        port: "A"
        index: 3
      z4:
        port: "A"
        index: 4
      z5:
        port: "A"
        index: 5

```
