### DISCUSSION TITLE
Mux on Mux issues with controls #9-15 (on 4067)

### DISCUSSION THREAD

**Discussion by eurorackworld** [shanteacontrols/OpenDeck#237] [Q&A] [answered]
Before I'm doing even more tests, just wanted to check my current issues here: 

**Setup**
I've a mux on mux setup with 4067 multiplexers, both on the nodes as on the main mux. I have 3 boards with each 2 multiplexers connect to that one single mux. 

**The issue**
For all controls (so per 4067 mux) only controls #0 to #7 work (so the first 8) the 2nd 8 analog controls aren't working. This is the case for all boards/multiplexers.

I've triple checked the S3 connection as this is the shift to that 2nd row (according to the technical docs I checked), but this looks all fine. The working controls do work great, it is just those 2nd 8 of all mux I cannot get to work. 

As there was a bug in the past on 'more than 2 muxes', just wanted to check if there is any known bug about maybe the S3 connection/pin when using a 4067? 

If there is any other suggestion which often seems to be forgotten that I can check, let me know :)

**Comment by paradajz** [comment]
Please share your entire config.

**Reply by eurorackworld** [reply]
<img width="205" alt="image" src="https://github.com/shanteacontrols/OpenDeck/assets/29734704/f8e0d4aa-2040-4712-b5f1-ab0c6c5552ef">

```
---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 1
        tx:
          port: "0"
          index: 0
  analog:
    type: "muxonmux"
    inputVoltage: "3.3"
    pins:
      controller:
        s0:
          port: "0"
          index: 18
        s1:
          port: "0"
          index: 19
        s2:
          port: "0"
          index: 20
        s3:
          port: "0"
          index: 21
        z:
          port: "0"
          index: 26
      nodes:
        s0:
          port: "0"
          index: 10
        s1:
          port: "0"
          index: 11
        s2:
          port: "0"
          index: 12
        s3:
          port: "0"
          index: 13
```
