### DISCUSSION TITLE
Combining type 'shiftRegister' with type 'native' for buttons in the config file?

### DISCUSSION THREAD

**Discussion by eurorackworld** [shanteacontrols/OpenDeck#243] [Q&A]
Hi,

i currently have a board with 6 shiftregisters on it for the buttons. This works perfectly. Somehow I had the idea to add just a few open contacts with connections directly to the RPI PICO's pins, to be able to add more buttons simply later. (so just free pins with a hole in the pcb in which i can solder any cable and configure anything in the YML, at least, before I was using shiftregisters). 

Now the questions is obvious; as I have 16 push encoders, these take up all room on the shiftregisters. I need to use to open pins to add 4 more buttons, is this even possible? Of course I tried various YML setup's, but no idea yet if this would even be possible?

Would it be fixable differently, by using the analog pins? Although those are just 3 points, while needing 4.. 

If I would solve this approach by adjusting the pcb and add another shiftregister, would it be fine to either not use those connections if not needed, or just a few? Or will unconnected pins directly cause issues (Although correctly pulled up for example)?

My YML is now this. And the buttons nicely show that there are 52 buttons (48 of the registers + 4 from the analog.. But 'obviously' those connections are not analog so I guess that will never going to work, or can I mention in the config that these are digital pins (ridiculous I know, but nobody got worse from asking dumb questions :P)

```
---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 1
        tx:
          port: "0"
          index: 0
  buttons:
    type: "shiftRegister"
    shiftRegisters: 6
    pins:
      data:
        port: "D"
        index: 18
      clock:
        port: "D"
        index: 19
      latch:
        port: "D"
        index: 20
  analog:
    type: "native"
    inputVoltage: "3.3"
    pins:
    -
      port: "0"
      index: 6
    -
      port: "0"
      index: 7
    -
      port: "0"
      index: 8
    -
      port: "0"
      index: 9
  leds:
    external:
      type: "native"
      pins:
      -
        port: "0"
        index: 10
      -
        port: "0"
        index: 11
      -
        port: "0"
        index: 12
      -
        port: "0"
        index: 13
```
