### DISCUSSION TITLE
Issue with 4051 Analog Multiplexer

### DISCUSSION THREAD

**Discussion by sebastianarnold** [shanteacontrols/OpenDeck#300] [General]
Hi everyone,

I'm using a raspi-pico connected to three 4051 multiplexers in the following schematic:

![image](https://github.com/shanteacontrols/OpenDeck/assets/837985/36bfaa63-649b-4bf0-8975-61785c34bafe)
![image](https://github.com/shanteacontrols/OpenDeck/assets/837985/8c3346c0-6e23-43a5-87e4-2fe133424703)

The MUX used are Nexperia 74HC4051D,653, which should be capable of handling 3.3V operation according to the datasheet:
https://www.mouser.de/datasheet/2/916/74HC_HCT4051-1318685.pdf

I'm using the following configuration:

```
---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 0
        tx:
          port: "0"
          index: 1
  buttons:
    type: "shiftRegister"
    shiftRegisters: 3
    pins:
      data: 
        port: "0"
        index: 10
      clock: 
        port: "0"
        index: 11
      latch: 
        port: "0"
        index: 12
  analog:
    type: "4051"
    inputVoltage: "3.3"
    multiplexers: 3
    pins:
      s0:
        port: "0"
        index: 20
      s1:
        port: "0"
        index: 21
      s2:
        port: "0"
        index: 22
      z0:
        port: "0"
        index: 26
      z1:
        port: "0"
        index: 27
      z2:
        port: "0"
        index: 28  
  leds:
    external:
      type: "shiftRegister"
      shiftRegisters: 6
      invert: false
      pins:
        data:
          port: "0"
          index: 14
        clock:
          port: "0"
          index: 15
        latch:
          port: "0"
          index: 19
        enable:
          port: "0"
          index: 18
```

All my digital inputs/outputs are working properly, but I have troubles getting the analog inputs to work. I get no readings in the OpenDeck Configurator activity when turning a pot.

Now I've tried some debugging based on the first pot connected to the mux at GP26, which leads me to the idea that this might be a software side problem, and not hardware related:

1. **The above configuration does not show any activity for any pot** connected to the mux at GP26/27/28
2. **Disabling multiplexer using native analog input works for the first pot.**
I switched the input type to 'native' instead of '4051'. That way the mux will connect the first input to GP26, and this does work. I get perfect readings for the first pot.

```
  analog:
    type: "native"
    inputVoltage: "3.3"
    pins:
      -
        port: "0"
        index: 26
```
3. **Disabling multiplexing using unused pins does not work.**
I tried to replicate the same behavior as (2) by setting the multiplexer pins to some unused pins. But like this I don't get any readings.
```
  analog:
    type: "4051"
    inputVoltage: "3.3"
    multiplexers: 1
    pins:
      s0:
        port: "0"
        index: 6
      s1:
        port: "0"
        index: 7
      s2:
        port: "0"
        index: 8
      z0:
        port: "0"
        index: 26
```

Does someone have any idea what's happening here? I even tried to replicate the Native.cpp implementation in Multiplexer.cpp, but for some unknown reason the readings will only work if I'm setting the type to native.

Best,
Sebastian

**Comment by paradajz** [comment]
Check the following discussion:
https://github.com/shanteacontrols/OpenDeck/discussions/177

**Comment by sebastianarnold** [comment]
Hi @paradajz, thanks for the quick relpy. I am aware that some models of the 4051 might need 5V for control. However, in my debug scenario (3), I'm setting s0..2 to 0V and I can clearly measure the 0..3.3V readout at GP26 when turning the pot, but the firmware does not pick it up. In scenario (2) the firmware will recognize this as native analog input, even with the mux connected and s0..2 set to 0V.

I expect in multiplexer mode that the firmware should pick up the value at GP26 for all mux channels, correct?

Is there anything the firmware/hardware does differently when `PROJECT_TARGET_DRIVER_ANALOG_INPUT_MULTIPLEXER` is set, expect for the multiplexer handling in `Multiplexer.cpp`?

**Comment by sebastianarnold** [comment]
One more update: I tried muxonmux (with the same schematic, so without any controller multiplexer in place) and set the controller inputs s0..1 to some unused pins. With this approach I am getting successful readings.

For me it looks like there might be an issue with with the implementation of multiplexer mode. I am happy to help tracking this down if you could give me some hints where to look at (see my post above).

```
  analog:
    type: "muxonmux"
    inputVoltage: "3.3"
    pins:
      controller:
        s0:
          port: "0"
          index: 6
        s1:
          port: "0"
          index: 7
        z:
          port: "0"
          index: 26
      nodes:
        s0:
          port: "0"
          index: 20
        s1:
          port: "0"
          index: 21
        s2:
          port: "0"
          index: 22
        s3:
          port: "0"
          index: 8
```
