### DISCUSSION TITLE
Two max7219 yaml

### DISCUSSION THREAD

**Discussion by pableitordasauto** [shanteacontrols/OpenDeck#313] [Q&A]
Hi @paradajz,
I have a board based on opendeck 2.2
I have modified with two max7219 in cascade. How I must type it in the yaml file.
The pins are connected in same configuration like 1 max only (48leds). Then the "dout" is connected to "din" and the control pins are shared.
With only 48 leds, it works well, but I don't know which number corresponding t9 the other max
Thanks!!!

**Comment by paradajz** [comment]
What is your current configuration?

**Reply by pableitordasauto** [reply]
The block for the leds is the following... I know that I must type drivers:2, but my doubt is about indexing.

```
leds:
    internal:
      invert: false
      pins:
        usb:
          rx:
            port: "0"
            index: 28
          tx:
            port: "0"
            index: 29
        uart:
          rx:
            port: "0"
            index: 28
          tx:
            port: "0"
            index: 29
    external:
      invert: true
      type: "max7219"
      drivers: 1
      pins:
        data:
          port: "0"
          index: 20
        clock:
          port: "0"
          index: 18
        latch:
          port: "0"
          index: 19
      indexing:
      - 24
      - 28
      - 30
      - 26
      - 27
      - 31
      - 29
      - 25
      - 56
      - 60
      - 62
      - 58
      - 59
      - 63
      - 61
      - 57
      - 16
      - 20
      - 22
      - 18
      - 19
      - 23
      - 21
      - 17
      - 32
      - 36
      - 38
      - 34
      - 35
      - 39
      - 37
      - 33
      - 0
      - 4
      - 6
      - 2
      - 3
      - 7
      - 5
      - 1
      - 40
      - 44
      - 46
      - 42
      - 43
      - 47
      - 45
      - 41
```
