### DISCUSSION TITLE
Shift Register Buttons Not Triggering Properly (RP2040, OpenDeck v7.10)

### DISCUSSION THREAD

**Discussion by kelvinyap9** [shanteacontrols/OpenDeck#315] [Q&A] [answered]
**Custom Firmware on v7.10 - RP2040 (Raspberry Pi Pico)**

**Problem:**

I can’t seem to get any pins on the shift register (74HC165N) to trigger a button (no light-up in the web config), except for Pin 6 (H), which always triggers Button 0.

This behavior is consistent with or without daisy-chaining the shift registers:
	•	With one shift register: Only Pin H (Pin 6) triggers Button 0.
	•	With two daisy-chained registers: Only Pin H on the second register triggers Button 0.

No other pins trigger any buttons.

Could this issue be caused by a timing mismatch (e.g., clock or latch signals)? Am I missing something in the YAML or wiring?

**What I’ve Tested:**

Multimeter Test:
- All button pins (A–H) idle at 3.3V (HIGH) and drop to 0V (LOW) when shorted to ground (button pressed).
This confirms pull-up resistors are working as expected.

Shift Register Behavior Without Daisy-Chaining:
- Same issue persists: Only Pin H (Pin 6) triggers Button 0.

-----

**YAML**
```
mcu: "rp2040"
usb: true
uart:
  dinMIDI:
    pins:
      rx:
        port: "0"
        index: 1
      tx:
        port: "0"
        index: 0
buttons:
  type: "shiftRegister"
  shiftRegisters: 2
  pins:
    data:
      port: "0"
      index: 11
    clock:
      port: "0"
      index: 12
    latch:
      port: "0"
      index: 13
analog:
  type: "4067"
  inputVoltage: "3.3"
  multiplexers: 2
  pins:
    s0:
      port: "0"
      index: 18
    s1:
      port: "0"
      index: 19
    s2:
      port: "0"
      index: 20
    s3:
      port: "0"
      index: 21
    z0:
      port: "0"
      index: 26
    z1:
      port: "0"
      index: 27
```

-----

**Wiring:**

**Shift Register → Pico**
```
Pin 1 (SH/LD - Latch) → GP13
Pin 2 (CLK - Clock) → GP12
Pin 9 (QH - Data Out) → GP11
Pins 3, 4, 5, 6, 11, 12, 13, 14 (A–H) → Buttons with 10kΩ pull-up resistors to 3.3V
Pin 16 (VCC) → Pico 3.3V
Pin 8 (GND) → Pico GND
```
I should also mentioned that I removed the following keys in my firmware (I'm not using these components) which were present in the pico.yaml which I used as a reference:

```
uart:
- touchscreen
- i2c

leds:

test: true (what is this?)

indexing (I see this in the opendeck board yaml for rp2040 but saw in another post in this discussion forum to not use undocumented keys)

```

I also added **inputVoltage: 3.3"** under **analog**. Should I leave that in or remove it?

Can I also remove **dinMIDI** ? I wasn't sure if that was just a pin allocated to physical MIDI ports. I don't plan to use it for that purpose as I just want this to be a USB-only MIDI controller.

Thanks!

**Comment by kelvinyap9** [comment]
For more context:

I built the firmware in Ubuntu 22.04 which I ran in a UTM VM on an Apple Silicon Mac with the docker dependencies installed, added my user to docker group, and following the instructions to clone the git, run the **dev.sh** script environment, **make clean** when I change anything in the yaml before I do **make TARGET=blabla.yaml** which spits out the build folder.

I then flashed the **merged.uf2** onto the Pico.

I'm also using this shift register diagram as a reference, hence the "Pins A to H".

![Screenshot 2024-11-26 at 19 45 59](https://github.com/user-attachments/assets/da6bcfca-2707-41f4-99fb-538ee8c8e506)

**Comment by kelvinyap9** [comment]
In an attempt to isolate this issue even further, I'm now using a very minimal yaml config with just 1x shift register, and no multiplexers.

```
mcu: "rp2040"
usb: true
buttons:
  type: "shiftRegister"
  shiftRegisters: 1
  pins:
    data:
      port: "0"
      index: 11
    clock:
      port: "0"
      index: 12
    latch:
      port: "0"
      index: 13
```

Interestingly, now only Pin 14 (D) and 6 (H) work. The others still nothing. Also tested with my other shift register to rule out faulty registers - same result, only Pin 14 and 6 trigger buttons.

Re-tested with multimeter and button presses definitely drop the voltage from HIGH to LOW - exactly same behaviour for non-working and working pins. I've also ruled out it's not a physical faulty button by using a wire to short the A-H input pins to GND to simulate a button press.
