### DISCUSSION TITLE
combining 'multiplexer' and 'native' analog inputs

### DISCUSSION THREAD

**Discussion by gitrimius** [shanteacontrols/OpenDeck#71] [Q&A]
HI,
Would it be possible to combine 4x4067 mux's and 1 native pin in the YAML file for defining a custom board variant? 
For example (for 2 mux's):

```
analog:
   type: "native"
   extReference: true
   pins:
   -
     port: "F"
     index: 0

  type: "4067"
  multiplexers: 2
  pins:
    s0:
      port: "B"
      index: 3
    s1:
      port: "B"
      index: 1
    s2:
      port: "E"
      index: 6
    s3:
      port: "B"
      index: 2
    z0:
      port: "F"
      index: 7
    z1:
      port: "F"
      index: 6
```
