### DISCUSSION TITLE
Issue with shift registers for LEDs

### DISCUSSION THREAD

**Discussion by gabooboo** [shanteacontrols/OpenDeck#87] [Q&A] [answered]
Hello,

Huge fan of this project!

I'm having an issue with getting single color LEDs to light up using the SparkFun Shift Register Breakout - 74HC595 (https://www.sparkfun.com/products/10680). I believe this is a supported shift register but I could be wrong.

I am using a custom board variant on an Arduino Mega 2560. Here is the LED section of my YAML file:
```
leds:
  external:
    type: "shiftRegister"
    shiftRegisters: 2
    pins:
      data:
        port: "H"
        index: 0
      clock:
        port: "J"
        index: 0
      latch:
        port: "H"
        index: 1
      enable:
        port: "J"
        index: 1
```

I've also attached an image of the breakout board and of my shift register circuit.

For the shift register breakout board, I have the "data" pin to "SER_IN", "clock" to "CLOCK", "latch" to "L_CLOCK" and "enable" to "/OE".

However, I can't get any LEDs to turn on when I try testing them in the web configurator.

Any idea what might be wrong or how I can further debug the issue? If you need more info from me, I'd be happy to provide it.

Thanks in advance!

![sparkfunShiftRegisterBreakout74HC595](https://user-images.githubusercontent.com/25521350/123742768-e0d6a700-d871-11eb-918c-ae32723c1946.jpg)
![shiftRegisterIssue](https://user-images.githubusercontent.com/25521350/123742811-e9c77880-d871-11eb-8c90-d73f9058e8ca.png)

**Comment by paradajz** [comment]
You need to set `shiftRegisters` to 1 if you're using only 1

**Comment by gabooboo** [comment]
Thank you for the fast response!

My mistake. I actually do have 2 shift registers connected. I just got lazy with my initial circuit diagram :(

Here is the correct circuit showing the 2 shift register breakout boards connected in series:

![shiftRegisterIssue2](https://user-images.githubusercontent.com/25521350/123817629-efe34680-d8bd-11eb-9262-8f47184da9ae.png)

**Comment by paradajz** [comment]
Can you send me your entire yml file?

**Comment by gabooboo** [comment]
Yes, here it is.

Using the mega2560_muxsh2.yml as an example, I added a section for unused-io even though there was no documentation for it. 

```
---
  arch: "avr"
  mcuFamily: "avr8"
  mcu: "atmega2560"
  usb: false
  dinMIDI:
    uartChannel: 1
  display:
    i2cChannel: 0
  touchscreen:
    uartChannel: 1
    components: 32
  buttons:
    type: "native"
    pins:
    -
      port: "B"
      index: 1
    -
      port: "B"
      index: 3
  analog:
    type: "4067"
    multiplexers: 2
    pins:
      s0:
        port: "E"
        index: 4
      s1:
        port: "G"
        index: 5
      s2:
        port: "H"
        index: 3
      s3:
        port: "H"
        index: 4
      z0:
        port: "F"
        index: 0
      z1:
        port: "F"
        index: 1
  leds:
    external:
      type: "shiftRegister"
      shiftRegisters: 2
      pins:
        data:
          port: "H"
          index: 0
        clock:
          port: "J"
          index: 0
        latch:
          port: "H"
          index: 1
        enable:
          port: "J"
          index: 1
  unused-io:
  -
    port: "A"
    index: 1
    state: "high"
  -
    port: "A"
    index: 3
    state: "high"
  -
    port: "A"
    index: 5
    state: "high"
  usbLink:
    type: "slave"
    uartChannel: 0
  bootloader:
    button:
      port: "B"
      index: 2
```
