### DISCUSSION TITLE
Trouble flashing custom STM32F411 variant

### DISCUSSION THREAD

**Discussion by gabooboo** [shanteacontrols/OpenDeck#94] [Q&A]
Hello again,

I decided to try my previous Mega controller on a Black Pill 411 instead.

So far I can build and flash the custom binary without any visible errors.

However after I flash the board, the Configurator only loads the very first time. After the first time, the board never appears in the Configurator even if I try resetting the board or disconnecting/reconnecting. In addition, the board now always has only one of the internal LEDs lit (like it does in bootloader mode), so something leads me to believe it did not flash properly.

I know the board is OK since I can still flash the public blackpill411 binary and that loads in the Configurator just fine (with both internal LEDs lit up).

I am building off of the most recent master. Here is my YML file:
```
---
  arch: "stm32"
  mcuFamily: "f4"
  mcu: "stm32f411ce"
  extClockMhz: 25
  usb: true
  buttons:
    type: "native"
    pins:
    -
      port: "B"
      index: 15
    -
      port: "A"
      index: 8
  analog:
    type: "4067"
    multiplexers: 8
    pins:
      s0:
        port: "A"
        index: 10
      s1:
        port: "A"
        index: 11
      s2:
        port: "A"
        index: 12
      s3:
        port: "A"
        index: 15
      z0:
        port: "A"
        index: 1
      z1:
        port: "A"
        index: 2
      z2:
        port: "A"
        index: 3
      z3:
        port: "A"
        index: 4
      z4:
        port: "A"
        index: 5
      z5:
        port: "A"
        index: 6
      z6:
        port: "A"
        index: 7
      z7:
        port: "B"
        index: 0
  leds:
    external:
      type: "shiftRegister"
      shiftRegisters: 9
      pins:
        data:
          port: "B"
          index: 13
        clock:
          port: "B"
          index: 10
        latch:
          port: "B"
          index: 14
        enable:
          port: "B"
          index: 12
  bootloader:
    button:
      port: "C"
      index: 14
```
Any ideas on what I could be doing wrong?

Thanks in advance!
